# Generated by Django 5.0.3 on 2024-05-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_perfilusuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbeiro'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(to='barbearia.servico'),
        ),
    ]
