# Generated by Django 5.0.3 on 2024-05-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Apontamento',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.DeleteModel(
            name='Barbeiro',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
